version: "3"
services:
  redis:
    image: redis:4.0-alpine
    expose:
      - "6379"


  db:
    image: mysql:8
    ports:
      - "3306"
    environment:
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
    volumes:
      - db-data:/var/lib/mysql

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx.Dockerfile
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - app-data:/app

  php:
    build:
      context: .
      dockerfile: ./docker/php.Dockerfile
    environment:
      WAIT_HOSTS: db:3306
    depends_on:
      - redis
      - db
      - composer
    expose:
      - "9000"
    volumes:
      - app-data:/app

volumes:
  app-data:
  db-data:
