version: "3"
services:
  nginx:
    environment:
      VIRTUAL_HOST: demo.local
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/app/public:ro

  php:
    volumes:
      - ./:/app
      - ./docker/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro

  composer:
    image: composer:1.7
    working_dir: /app
    environment:
      SSH_AUTH_SOCK: /ssh-auth.sock
    volumes:
      - ./:/app
      - "$SSH_AUTH_SOCK:/ssh-auth.sock"
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    command: composer install --ignore-platform-reqs --no-scripts
